### ISSUE TITLE
 TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by matthewbecker1990** [jeduan/google-play-publisher#6]
Hi,

Just wondering what format this requires the private key in?

I have tried .JSON, .p12 and .pem and I am getting the error: 

[Error: invalid_grant].

When I feed it the private key as a string, I get the error:

_stream_readable.js:495
  dest.on('unpipe', onunpipe);
      ^
TypeError: Cannot read property 'on' of undefined

I'm not sure what I am doing wrong. Any help would be much appreciated!

Thanks,
Matt

**Comment by matthewbecker1990** [comment]
I should note that I am using the API, not the CLI.

**Comment by matthewbecker1990** [comment]
I'm receiving the same error when using the CLI also.

google-play-publisher --auth C:\Development\publish_service.json --recent-changes "en-US=Some changes go here" C:\Development\APPS\XXX\platforms\android\ant-build\MainActivity-release.apk

_stream_readable.js:476
  dest.on('unpipe', onunpipe);
       ^
TypeError: Cannot call method 'on' of undefined

**Comment by jeduan** [comment]
it expects JSON. Apparently you don't have the permission on the key? interesting.

**Comment by matthewbecker1990** [comment]
Very strange, I have granted admin to the service email in the play developer website.

Sent from my HTC on the Telstra Mobile network

----- Reply message -----

**Comment by jeduan** [comment]
Just to be clear, is that on Settings -> API access on the Play Developer Console?

**Comment by matthewbecker1990** [comment]
Correct. Then I go into the cloud console and create the service account, and it gives me the json file. Then I go back to the play developer console and click grant access and select admin.

 Thank you for your help.

Sent from my HTC on the Telstra Mobile network

----- Reply message -----

**Comment by matthewbecker1990** [comment]
This is the full error I am receiving when running the command:

`google-play-publisher --auth "C:/Development/publish_service.json" --recent-changes "en-US=Some changes go here" "C:/Development/APPS/LansvalePublicSchool/platforms/android/ant-build/MainActivity-release.apk"`

Error:

`_stream_readable.js:495
  dest.on('unpipe', onunpipe);
      ^
TypeError: Cannot read property 'on' of undefined
    at ReadStream.Readable.pipe (_stream_readable.js:495:7)
    at createAPIRequest (C:\Users\Matthew\AppData\Roaming\npm\node_modules\googl
e-play-publisher\node_modules\googleapis\lib\apirequest.js:195:10)
    at Object.Androidpublisher.edits.apks.upload (C:\Users\Matthew\AppData\Roami
ng\npm\node_modules\google-play-publisher\node_modules\googleapis\apis\androidpu
blisher\v2.js:465:16)
    at uploadAPK (C:\Users\Matthew\AppData\Roaming\npm\node_modules\google-play-
publisher\index.js:77:28)
    at fn (C:\Users\Matthew\AppData\Roaming\npm\node_modules\google-play-publish
er\node_modules\async\lib\async.js:641:34)
    at Immediate._onImmediate (C:\Users\Matthew\AppData\Roaming\npm\node_modules
\google-play-publisher\node_modules\async\lib\async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)`

**Comment by matthewbecker1990** [comment]
Looks like it could be this issue:

I did a bit of digging, added some logging to your index.js and found that it is authenticating fine, but failing the upload because it cant find `dest`

https://github.com/google/google-api-nodejs-client/issues/260

**Comment by matthewbecker1990** [comment]
Okay... with the help of a friend we have solved the issue. Here's what seems to be happening:

1. OAuth2Client.prototype.request in oauth2client.js (google-play-publisher\node_modules\googleapis\node_modules\google-auth-library\lib\auth) is calling `this.getRequestMetadata(unusedUri, cb_with_auth);` which is located in jwtclient.js (google-play-publisher\node_modules\googleapis\node_modules\google-auth-library\lib\auth) at line 78

2. This is then calling `JWT.super_.prototype.getRequestMetadata.call(this, opt_uri, cb_with_metadata); ` however this function is not returning, so the value is never bubbling back down to the OAuth2Client.prototype.request function.

Solution:

Line 87 from:
`JWT.super_.prototype.getRequestMetadata.call(`
to 
`return JWT.super_.prototype.getRequestMetadata.call(`

**Comment by tbetbetbe** [comment]
Thanks for this analysis and for reporting the issue.  Is this just analysis, or have you verified that the suggested edit (on its own) resolves this issue.

**Comment by matthewbecker1990** [comment]
I can confirm that it resolves the issue.

**Comment by ronkorving** [comment]
That's been released now, so doing a fresh install of google-play-publisher should resolve it (since it's a patch level upgrade and all versions are semver-linked with `~`)

**Comment by jeduan** [comment]
Agreed. You can also go to `node_modules/googleapis` and do `npm update google-auth-library`. Maybe I should consider migrating the library to just use request. Google's libs are just a thin wrapper around that.
